### ISSUE TITLE
Uncaught exception on login

### ISSUE THREAD

**Issue by murjam** [bisand/node-red-contrib-panasonic-comfort-cloud#32]
Trying to use the nodes but when I do, I get this error (which is uncaught and crashes the whole Node-RED instance):

```
[red] Uncaught Exception:
[error] Error: code is null.
    at OAuthClient.oAuthProcess (/data/node_modules/panasonic-comfort-cloud-client/dist/src/OAuthClient.js:66:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ComfortCloudClient.login (/data/node_modules/panasonic-comfort-cloud-client/dist/src/ComfortCloudClient.js:63:27)
    at async ComfortCloudGroups._inputCallback (/data/node_modules/node-red-contrib-panasonic-comfort-cloud/src/comfort-cloud-groups.js:16:13)
```

**Comment by bisand** [comment]
I have just released a new version (v2.0.4) that should fix the login problems and crashes. Upgrade and take it for a spin, and report back on your findings.

Thanks! :)
